name: pdfarranger
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    container: jeromerobert/pdfarranger-docker-ci
    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: pip3 install .
